"""Make image_url nullable

Revision ID: 17c224642864
Revises: de79b4a9f31c
Create Date: 2025-10-06 23:41:49.925862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c224642864'
down_revision = 'de79b4a9f31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tides', schema=None) as batch_op:
        batch_op.drop_index('ix_tides_datetime')
        batch_op.drop_index('ix_tides_station_id')

    op.drop_table('tides')
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('tides',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('station_id', sa.VARCHAR(), nullable=False),
    sa.Column('datetime', sa.DATETIME(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('tide_type', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tides')
    )
    with op.batch_alter_table('tides', schema=None) as batch_op:
        batch_op.create_index('ix_tides_station_id', ['station_id'], unique=False)
        batch_op.create_index('ix_tides_datetime', ['datetime'], unique=False)

    # ### end Alembic commands ###
