"""update Catch model fields

Revision ID: 1edf4605f0f4
Revises: 17c224642864
Create Date: 2025-10-07 18:53:36.948046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf4605f0f4'
down_revision = '17c224642864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_temp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('air_temp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('moon_phase', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('longitude')
        batch_op.drop_column('location_description')
        batch_op.drop_column('weather')
        batch_op.drop_column('gear')
        batch_op.drop_column('latitude')
        batch_op.drop_column('bait_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bait_used', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gear', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location_description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('size')
        batch_op.drop_column('moon_phase')
        batch_op.drop_column('air_temp')
        batch_op.drop_column('water_temp')

    # ### end Alembic commands ###
