"""Add notifications table

Revision ID: 20a383188cab
Revises: 86a3b6d09bef
Create Date: 2025-12-28 01:09:47.821231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a383188cab'
down_revision = '86a3b6d09bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('idx_notifications_unread')
        batch_op.create_index('idx_notifications_unread', ['recipient_id', 'is_read'], unique=False)
        batch_op.drop_index('idx_notifications_user')
        batch_op.create_index('idx_notifications_user', ['recipient_id'], unique=False)
        batch_op.drop_constraint('fk_notifications_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_recipient_id_users'), 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_notifications_recipient_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_notifications_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_index('idx_notifications_user')
        batch_op.create_index('idx_notifications_user', ['user_id'], unique=False)
        batch_op.drop_index('idx_notifications_unread')
        batch_op.create_index('idx_notifications_unread', ['user_id', 'is_read'], unique=False)
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
