"""update Catch model field to include bait used

Revision ID: 44273ee44afa
Revises: 1edf4605f0f4
Create Date: 2025-10-07 19:19:06.657061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44273ee44afa'
down_revision = '1edf4605f0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bait_used', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.drop_column('bait_used')

    # ### end Alembic commands ###
