"""Add profile_photo and cover_photo to User model

Revision ID: 47f0bacec592
Revises: 3b59281a5037
Create Date: 2025-11-04 23:24:19.328658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f0bacec592'
down_revision = '3b59281a5037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_followers_follower_id_users')),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('fk_followers_following_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followers'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_photo')
        batch_op.drop_column('profile_photo')

    op.drop_table('followers')
    # ### end Alembic commands ###
