"""add location field to Catch model

Revision ID: 5b8ae824eb49
Revises: be284b58f755
Create Date: 2025-10-26 22:19:20.720688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8ae824eb49'
down_revision = 'be284b58f755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
