"""add user leveling columns

Revision ID: 6c99b71dabb5
Revises: 13b48bf279e1
Create Date: 2025-12-15 14:38:12.023337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c99b71dabb5'
down_revision = '13b48bf279e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prestige', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('posts_toward_next_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('posts_toward_next_level')
        batch_op.drop_column('prestige')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
