"""Add is_public column to Catch

Revision ID: 8708e570396a
Revises: 5b8ae824eb49
Create Date: 2025-10-31 16:45:19.042495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8708e570396a'
down_revision = '5b8ae824eb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
