"""Initial migration

Revision ID: 8c939724307f
Revises: 
Create Date: 2025-08-09 17:31:02.517289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c939724307f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('date_caught', sa.DateTime(), nullable=True),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('tide', sa.String(), nullable=True),
    sa.Column('bait_used', sa.String(), nullable=True),
    sa.Column('gear', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catches'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catches')
    # ### end Alembic commands ###
