"""Add caption to catches

Revision ID: 99d6c4d505ec
Revises: 20a383188cab
Create Date: 2026-07-30 22:08:24.130498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d6c4d505ec'
down_revision = '20a383188cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('posts_toward_next_level')
        batch_op.drop_column('prestige')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prestige', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('posts_toward_next_level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
