"""replace size with length/weight and add wind_speed + method

Revision ID: be284b58f755
Revises: 44273ee44afa
Create Date: 2025-10-23 20:22:10.989222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be284b58f755'
down_revision = '44273ee44afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wind_speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(), nullable=True))
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('method')
        batch_op.drop_column('wind_speed')
        batch_op.drop_column('weight')
        batch_op.drop_column('length')

    # ### end Alembic commands ###
