"""Add Tide model

Revision ID: de79b4a9f31c
Revises: 8c939724307f
Create Date: 2025-08-11 22:25:33.381982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de79b4a9f31c'
down_revision = '8c939724307f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('tide_type', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tides'))
    )
    with op.batch_alter_table('tides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tides_datetime'), ['datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_tides_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tides_station_id'))
        batch_op.drop_index(batch_op.f('ix_tides_datetime'))

    op.drop_table('tides')
    # ### end Alembic commands ###
