import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#020b13",
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 32,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#000",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  headerTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  cancelText: {
    color: "#f5b20b",
    fontWeight: "600",
    fontSize: 16,
  },
  imagePlaceholder: {
    height: 118,
    borderWidth: 1,
    borderColor: "#0873aa",
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 12,
  },
  uploadBackground: { flex: 1 },
  uploadBackgroundImage: { opacity: 0.4 },
  uploadOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 27, 48, 0.65)",
  },
  cameraBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "#20bfff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 7,
  },
  imagePlaceholderText: {
    color: "#d8f4ff",
    fontSize: 14,
    fontWeight: "700",
  },
  uploadHint: {
    color: "#9cc9df",
    fontSize: 11,
    marginTop: 2,
  },
  previewImage: {
    width: "100%",
    height: 118,
    borderRadius: 10,
    marginBottom: 12,
  },
  captionContainer: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#08689b",
    backgroundColor: "#04182a",
    borderRadius: 9,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  captionInput: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: "#e8f8ff",
    fontSize: 13,
  },
  input: {
    borderWidth: 1,
    borderColor: "#08689b",
    backgroundColor: "#04182a",
    borderRadius: 8,
    paddingHorizontal: 8,
    marginVertical: 4,
    height: 44,
    color: "#d8f4ff",
    fontSize: 12,
    textAlign: "center" as const,
  },
  inputText: {
    color: "#d8f4ff",
    textAlign: "center",
    fontSize: 14,
  },
  placeholderText: {
    color: "#83a8bd",
    textAlign: "center",
    fontSize: 14,
  },
  fileName: {
    color: "white",
    textAlign: "center" as const,
  },
  rowContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  halfInput: {
    width: "48%",
  },
  fullInput: { width: "100%" },
  visibilityTitle: { color: "#edfaff", fontSize: 16, fontWeight: "600", marginBottom: 12 },
  visibilityOptions: { flexDirection: "row", gap: 12 },
  visibilityOption: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, padding: 14, borderRadius: 12, borderWidth: 1, borderColor: "#254355" },
  visibilitySelected: { backgroundColor: "#103348", borderColor: "#7cddf5" },
  visibilityLabel: { color: "#edfaff", fontWeight: "600" },
  visibilityHelp: { color: "#83a8bd", marginTop: 10, fontSize: 13 },
  sectionCard: {
    borderWidth: 1,
    borderColor: "#07577f",
    backgroundColor: "#031426",
    borderRadius: 9,
    padding: 8,
    marginBottom: 10,
  },
  sectionHeader: {
    minHeight: 26,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
    marginBottom: 4,
  },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTitle: { color: "#e1f6ff", fontWeight: "700", fontSize: 14 },
  addButton: {
    backgroundColor: "#12aef2",
    paddingVertical: 13,
    borderRadius: 9,
    marginTop: 2,
    alignItems: "center",
  },
  addButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  disabledButton: {
    backgroundColor: "#555",
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "700",
  },
  // previewImage: {   initial style for selected images
  // width: 150,
  // height: 150,
  // borderRadius: 12,
  // alignSelf: "center",
  // marginBottom: 10,
  // borderWidth: 1,
  // borderColor: "gray",
  // },
  dropdownButton: {
    borderWidth: 1,
    borderColor: "gray",
    padding: 8,
    marginVertical: 4,
    height: 40,
    color: "white",
    textAlign: "center" as const,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContainer: {
    backgroundColor: "#04182a",
    borderColor: "#0873aa",
    borderWidth: 1,
    padding: 20,
    borderRadius: 12,
    width: "80%",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
    color: "white",
  },
  moonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
  },
  moonItem: {
    alignItems: "center",
    marginVertical: 8,
  },
  moonImage: {
    width: 50,
    height: 50,
    marginBottom: 4,
  },
  moonLabel: {
    fontSize: 10,
    color: "white",
  },
  cancelButton: {
    marginTop: 16,
    alignSelf: "center",
  },
  dropdownItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#08689b",
    alignItems: "center",
  },
  dropdownItemText: {
    color: "white",
    fontSize: 16,
  },
  successMessage: {
    color: "#4CAF50",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 10,
  },
});
